// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp0mOkdRClP3100aElzh25HPkRiCqP6WA',
    appId: '1:466867203642:web:9a6c9d13483d2d99e40f03',
    messagingSenderId: '466867203642',
    projectId: 'realstate-e5bbc',
    authDomain: 'realstate-e5bbc.firebaseapp.com',
    storageBucket: 'realstate-e5bbc.appspot.com',
    measurementId: 'G-0F9Y2YM4DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSKdlUrrAB7a7W7M2h30y-q04-_MIwQzo',
    appId: '1:466867203642:android:bbc6597ee65c7de1e40f03',
    messagingSenderId: '466867203642',
    projectId: 'realstate-e5bbc',
    storageBucket: 'realstate-e5bbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwhjrLFZcMxp_QV1CV9B3jBnX-r9uyAXk',
    appId: '1:466867203642:ios:04758762e4585abae40f03',
    messagingSenderId: '466867203642',
    projectId: 'realstate-e5bbc',
    storageBucket: 'realstate-e5bbc.appspot.com',
    iosBundleId: 'com.brokers.realstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwhjrLFZcMxp_QV1CV9B3jBnX-r9uyAXk',
    appId: '1:466867203642:ios:c337e031ae3b9a50e40f03',
    messagingSenderId: '466867203642',
    projectId: 'realstate-e5bbc',
    storageBucket: 'realstate-e5bbc.appspot.com',
    iosBundleId: 'com.brokers.realstate.RunnerTests',
  );
}
